### ISSUE TITLE
CSS Confusion @thatkidmadrid

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/kraken-good-accessibility#1]
Hi, im having trouble with the css and making the screen shot in markbot match with my content @thatkidmadrid

**Comment by thatkidmadrid** [comment]
Sorry if I wasn't clear in class, but we discussed how almost all of the css is already completed for this exercise. As you replace the generic `<div>`s and `<p>`s with the proper tags, the styling will apply on their own. The only css you will need to write is for the [hover/focus states](https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles)

**Comment by adrianna16** [comment]
Ohh right okay, sorry I must have missed that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
