### ISSUE TITLE
Buttons @thatkidmadrid

### ISSUE THREAD

**Issue by adrianna16** [adrianna16/kraken-good-accessibility#2]
sorry if you mentioned this in class aswell, I rewatched the lecture and didn't hear anything. but I cannot seem to get the buttons to match with the screen shots. @thatkidmadrid

**Comment by thatkidmadrid** [comment]
Hey Adrianna,

You will want to take a look at the css property `outline` I think you're on the right track with adding the background, but adding the outline is a standard way to highlight the keyboard focus for the user (w3 docs on outline). You can think of the outline as being a border for the border

In the video as well as the lesson under the video there's an example of the outline being used for the focus and hover states. You will want to use the same approach to match the styling of the navigation in the reference :)

https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles

**Comment by adrianna16** [comment]
thank you very much :) i appreciate your help
________________________________

**Comment by adrianna16** [comment]
i did the hover and everything but the thickness of the icons still dont match up and i am not understanding why i added the icons you gave us in class
________________________________

**Comment by thatkidmadrid** [comment]
Oh, that's what you meant. The new icons have a smaller stroke than the reference. You can ignore that and focus on the structure of the rest of the content, the landmark roles, the descriptions, and all the accessibility related tasks.

You can use Voiceover on the page to see for yourself if what you have makes sense before you submit

**Comment by adrianna16** [comment]
Oh okay, so then markbot is having a different issue then my icons not matching?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thatkidmadrid** [comment]
can you please provide a screenshot for more context?

we covered in class and brightspace that you won't be able to submit through markbot, so use your judgement and knowledge of web accessibility from week-04 to know when to stop and tag me in an issue for submission

**Comment by adrianna16** [comment]
okay thank you
________________________________
